avathar_bbguild_wow_emblem:
    path: /bbguild_wow/emblem/{guild_id}
    defaults: { _controller: avathar.bbguild_wow.asset_controller:serve_emblem }
    requirements:
        guild_id: \d+

avathar_bbguild_wow_portrait:
    path: /bbguild_wow/portrait/{player_id}
    defaults: { _controller: avathar.bbguild_wow.asset_controller:serve_portrait }
    requirements:
        player_id: \d+

avathar_bbguild_wow_achiev_categories:
    path: /bbguild_wow/achievements/categories/{guild_id}
    defaults: { _controller: avathar.bbguild_wow.achievement_controller:categories }
    requirements:
        guild_id: \d+

avathar_bbguild_wow_achiev_list:
    path: /bbguild_wow/achievements/list/{guild_id}/{category_id}
    defaults: { _controller: avathar.bbguild_wow.achievement_controller:achievement_list }
    requirements:
        guild_id: \d+
        category_id: \d+

avathar_bbguild_wow_sync_roster:
    path: /bbguild_wow/sync-roster/{guild_id}
    defaults: { _controller: avathar.bbguild_wow.portrait_controller:sync_roster }
    requirements:
        guild_id: \d+

avathar_bbguild_wow_sync_specs:
    path: /bbguild_wow/sync-specs/{guild_id}
    defaults: { _controller: avathar.bbguild_wow.portrait_controller:sync_specs }
    requirements:
        guild_id: \d+

avathar_bbguild_wow_sync_portraits:
    path: /bbguild_wow/sync-portraits/{guild_id}
    defaults: { _controller: avathar.bbguild_wow.portrait_controller:sync }
    requirements:
        guild_id: \d+

avathar_bbguild_wow_sync_categories:
    path: /bbguild_wow/sync-categories/{guild_id}
    defaults: { _controller: avathar.bbguild_wow.achievement_sync_controller:sync_categories }
    requirements:
        guild_id: \d+

avathar_bbguild_wow_sync_achievements:
    path: /bbguild_wow/sync-achievements/{guild_id}
    defaults: { _controller: avathar.bbguild_wow.achievement_sync_controller:sync_achievements }
    requirements:
        guild_id: \d+

avathar_bbguild_wow_achiev_detail:
    path: /bbguild_wow/achievements/detail/{guild_id}/{achievement_id}
    defaults: { _controller: avathar.bbguild_wow.achievement_controller:achievement_detail }
    requirements:
        guild_id: \d+
        achievement_id: \d+
