avathar_bbguildwow_emblem:
    path: /bbguildwow/emblem/{guild_id}
    defaults: { _controller: avathar.bbguildwow.asset_controller:serve_emblem }
    requirements:
        guild_id: \d+

avathar_bbguildwow_portrait:
    path: /bbguildwow/portrait/{player_id}
    defaults: { _controller: avathar.bbguildwow.asset_controller:serve_portrait }
    requirements:
        player_id: \d+

avathar_bbguildwow_render:
    path: /bbguildwow/render/{player_id}
    defaults: { _controller: avathar.bbguildwow.asset_controller:serve_render }
    requirements:
        player_id: \d+

avathar_bbguildwow_achiev_categories:
    path: /bbguildwow/achievements/categories/{guild_id}
    defaults: { _controller: avathar.bbguildwow.achievement_controller:categories }
    requirements:
        guild_id: \d+

avathar_bbguildwow_achiev_list:
    path: /bbguildwow/achievements/list/{guild_id}/{category_id}
    defaults: { _controller: avathar.bbguildwow.achievement_controller:achievement_list }
    requirements:
        guild_id: \d+
        category_id: \d+

avathar_bbguildwow_sync_roster:
    path: /bbguildwow/sync-roster/{guild_id}
    defaults: { _controller: avathar.bbguildwow.portrait_controller:sync_roster }
    requirements:
        guild_id: \d+

avathar_bbguildwow_sync_specs:
    path: /bbguildwow/sync-specs/{guild_id}
    defaults: { _controller: avathar.bbguildwow.portrait_controller:sync_specs }
    requirements:
        guild_id: \d+

avathar_bbguildwow_sync_portraits:
    path: /bbguildwow/sync-portraits/{guild_id}
    defaults: { _controller: avathar.bbguildwow.portrait_controller:sync }
    requirements:
        guild_id: \d+

avathar_bbguildwow_sync_equipment:
    path: /bbguildwow/sync-equipment/{guild_id}
    defaults: { _controller: avathar.bbguildwow.portrait_controller:sync_equipment }
    requirements:
        guild_id: \d+

avathar_bbguildwow_sync_categories:
    path: /bbguildwow/sync-categories/{guild_id}
    defaults: { _controller: avathar.bbguildwow.achievement_sync_controller:sync_categories }
    requirements:
        guild_id: \d+

avathar_bbguildwow_sync_achievements:
    path: /bbguildwow/sync-achievements/{guild_id}
    defaults: { _controller: avathar.bbguildwow.achievement_sync_controller:sync_achievements }
    requirements:
        guild_id: \d+

avathar_bbguildwow_sync_player_achievements:
    path: /bbguildwow/sync-player-achievements/{guild_id}
    defaults: { _controller: avathar.bbguildwow.achievement_sync_controller:sync_player_achievements }
    requirements:
        guild_id: \d+

avathar_bbguildwow_achiev_detail:
    path: /bbguildwow/achievements/detail/{guild_id}/{achievement_id}
    defaults: { _controller: avathar.bbguildwow.achievement_controller:achievement_detail }
    requirements:
        guild_id: \d+
        achievement_id: \d+

avathar_bbguildwow_character_stats:
    path: /bbguildwow/character-stats/{player_id}
    defaults: { _controller: avathar.bbguildwow.character_stats_controller:stats }
    requirements:
        player_id: \d+
