imports:
    - { resource: tables.yml }

services:
    avathar.bbguild_wow.installer:
        class: avathar\bbguild_wow\game\wow_installer

    avathar.bbguild_wow.api:
        class: avathar\bbguild_wow\game\wow_api
        arguments:
            - '@cache'

    avathar.bbguild_wow.provider:
        class: avathar\bbguild_wow\game\wow_provider
        arguments:
            - '@avathar.bbguild_wow.installer'
            - '@avathar.bbguild_wow.api'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }

    avathar.bbguild_wow.achievement:
        class: avathar\bbguild_wow\model\achievement
        arguments:
            - '%avathar.bbguild_wow.tables.bb_achievement_track%'
            - '%avathar.bbguild_wow.tables.bb_achievement%'
            - '%avathar.bbguild_wow.tables.bb_achievement_rewards%'
            - '%avathar.bbguild_wow.tables.bb_criteria_track%'
            - '%avathar.bbguild_wow.tables.bb_achievement_criteria%'
            - '%avathar.bbguild_wow.tables.bb_relations_table%'
