parameters:
    avathar.bbguildwow.tables.bb_guild_wow: '%core.table_prefix%bb_guild_wow'
    avathar.bbguildwow.tables.bb_achievement_track: '%core.table_prefix%bb_achievement_track'
    avathar.bbguildwow.tables.bb_achievement: '%core.table_prefix%bb_achievement'
    avathar.bbguildwow.tables.bb_achievement_rewards: '%core.table_prefix%bb_achievement_rewards'
    avathar.bbguildwow.tables.bb_criteria_track: '%core.table_prefix%bb_criteria_track'
    avathar.bbguildwow.tables.bb_achievement_criteria: '%core.table_prefix%bb_achievement_criteria'
    avathar.bbguildwow.tables.bb_relations_table: '%core.table_prefix%bb_relations_table'
    avathar.bbguildwow.tables.bb_achievement_category: '%core.table_prefix%bb_achievement_category'
    avathar.bbguildwow.tables.bb_player_equipment: '%core.table_prefix%bb_player_equipment'
    avathar.bbguildwow.tables.bb_player_item_stat: '%core.table_prefix%bb_player_item_stat'
